Task #891338
zerg0s/LetsLearnGit pull request #1
Opened 2020-10-16 12:37 UTC by Hsiflix

Task #891338 (Кириченко Виктор)

2020-10-16 12:54 UTC, zerg0s commented on AlphabetV2.py
> +def function_(start__, finish__, memory__, first_iter__):
Название переменных :(

2020-10-16 12:55 UTC, zerg0s commented on AlphabetV2.py
> +    if start__[0]!=finish__[0]:
а где пробелы вокруг "!="  ?

2020-10-16 12:55 UTC, zerg0s commented on AlphabetV2.py
> +                    first_iter=first_iter__, last_iter=True)
аналогично

2020-10-16 12:57 UTC, zerg0s requested changes

2020-10-16 12:57 UTC, zerg0s commented on main.py
> +    AlphabetV2.alphabetV2(start, finish)
No new line at the end of file

2020-10-16 12:57 UTC, zerg0s commented on AlphabetV2.py
> +'''
название файла с маленькой буквы

2020-10-16 13:49 UTC, Hsiflix commented
Ошибки поправил, кроме "No new line at the end of file". У меня в редакторе они есть, также если открыть файлы на редактирование в github, то они есть. Их нет только на предварительном просмотре. Можете, пожалуйста, подсказать почему так происходит?

И потом мне нужно закрыть этот реквест и открыть новый?

2020-10-20 08:26 UTC, zerg0s commented on alphabet.py
> +def function_(beginning, ending, begin_with, first_iteration):
Так и не поменял название функции

2020-10-20 08:49 UTC, merged