Выполненое задание
zerg0s/LetsLearnGit pull request #2
Opened 2020-10-16 16:17 UTC by Lexer-pixel

Серёгин Сергей
16.10.2020
Алфавит

2020-10-16 21:08 UTC, Lexer-pixel commented
Вроде всё....

2020-10-16 21:53 UTC, Lexer-pixel commented
Вспомнил, что строки должны быть одной длины...

Вот теперь точно всё...

2020-10-20 08:54 UTC, zerg0s requested changes

2020-10-20 08:54 UTC, zerg0s commented on README.txt
> +������� ������ �� ��������
Кодировочка(

2020-10-20 08:54 UTC, zerg0s commented on main.py
> -if __name__ == "__main__":
так вообще не пойдет - не надо перетирать имееющийся мейн - только дополнять

2020-10-20 10:30 UTC, closed without merging