pull request
zerg0s/LetsLearnGit pull request #4
Opened 2020-10-19 19:15 UTC by igame9

Ruban A.A

2020-10-20 08:59 UTC, zerg0s commented on abcExample.py
> -def abc(start, finish):
Не надо мой алфавит удалять.
Еще возьми новый main иначе - конфликты

2020-10-20 11:43 UTC, igame9 commented on abcExample.py
> -def abc(start, finish):
Вроде исправил

2020-10-20 12:08 UTC, igame9 commented on abcExample.py
> -def abc(start, finish):
а все я понял, ща исправлю все

2020-10-23 06:46 UTC, zerg0s approved these changes

2020-10-23 06:48 UTC, zerg0s requested changes
+master уже обновился

2020-10-23 06:48 UTC, zerg0s commented on main.py
> +        abcStartFinish.abcv4(start, finish)
тут в main уже есть один try-catch зачем второй?

2020-10-23 09:46 UTC, zerg0s approved these changes

2020-10-23 09:47 UTC, zerg0s commented
Еще в редмайне задачку надо обновить

2020-10-23 09:48 UTC, merged

2020-10-23 09:53 UTC, igame9 commented
Я перевел на вас ее в редмайне