Add solution by Dimanchella. Task: "Alphabet".
zerg0s/LetsLearnGit pull request #66
Opened 2022-10-30 09:25 UTC by Dimanchella

2022-11-01 11:50 UTC, zerg0s requested changes

2022-11-01 11:50 UTC, zerg0s commented on alphabet_dimanchella.py
> +A_CODE = 97
магическая константа, лучше ord("a) или хотя бы в комментарий написать # code of "a'

2022-11-01 11:50 UTC, zerg0s commented on main.py
> +    print("Dimanchella's solution")
A ValueError? Кидаешь, но его никто не ловит...

2022-11-01 13:16 UTC, Dimanchella commented on main.py
> +    print("Dimanchella's solution")
Я отлавливаю ValueError в функции вывода print_iterating_strs. При ошибке она просто выводит "ERROR!".

2022-11-03 05:39 UTC, zerg0s commented on main.py
> +    print("Dimanchella's solution")
Да, это ок

2022-11-03 17:19 UTC, closed without merging