Rodionov branch
zerg0s/LetsLearnGit pull request #8
Opened 2020-10-22 20:48 UTC by Vadim000009

Работу выполнил, предоставляю пул реквест. Корректная работа возможна при данных, введённых в соответствии с требованием задачи. При введении некорректных данных работа, соответственно, будет некорректной.

2020-10-23 06:25 UTC, zerg0s requested changes
+надо обновиться актуального мастера

2020-10-23 06:25 UTC, zerg0s commented on main.py
> +    # a, b = input(), input()
Это не надо такое

2020-10-23 06:25 UTC, zerg0s commented on .idea/.gitignore
> +/workspace.xml
эти файлы тоже не надо комиттить

2020-10-23 06:25 UTC, zerg0s commented on .idea/.gitignore
> +/dataSources/
как и эти

2020-10-23 06:25 UTC, zerg0s commented on main.py
> +from funcRodionov import getArrWords
А где мой алфавит?

2020-10-23 10:22 UTC, Vadim000009 commented on main.py
> +from funcRodionov import getArrWords
Он тут, но сейчас это чуточку исправлю.
abcByRVS.alphabet

2020-10-26 14:40 UTC, zerg0s requested changes
Проверь еще раз, чтобы только нужное закомитить

2020-10-26 14:40 UTC, zerg0s commented on abcBySmolnaya.py
> +    return newAbc
а зачем чужие файлы трогать?

2020-10-26 14:42 UTC, Vadim000009 commented on abcBySmolnaya.py
> +    return newAbc
Я так и не понял, почему здесь ругалось на эту строчку, но в ней почему то конфликт, хотя они идентичны :/

2020-10-26 14:51 UTC, zerg0s commented on abcBySmolnaya.py
> +    return newAbc
Не добавлять чужие файлы в staged и не коммитить изменения в них.
Сейчас проще всего взять новый бранч от мастера и накатить туда свои изменения.

2020-10-26 14:56 UTC, Vadim000009 commented on abcBySmolnaya.py
> +    return newAbc
Понял, сделаю ближе к 20. Сейчас немного в другой работе

2020-10-28 07:14 UTC, zerg0s requested changes
Предлагаю создать новый PR, не нужны лишние изменения.

2020-10-28 07:19 UTC, closed without merging

2020-10-28 07:19 UTC, zerg0s commented
Предлагаю создать новый PR, не нужны лишние изменения.